services:
  - type: web
    name: fruit-game
    runtime: node
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 718081012338-tgmapnfrd7rc39fvf8h2sju6evap3q6j.apps.googleusercontent.com
      - key: JWT_SECRET
        generateValue: true
